### ISSUE TITLE
Allow specifying XML version or default to XML v1.0

### ISSUE THREAD

**Issue by leoschwarz** [jonas-schievink/xml-rpc-rs#12]
I know that XML v1.1 has been there quite some while now, but in the original [XML-RPC Specification](http://xmlrpc.scripting.com/spec.html) only XML v1.0 was used in the examples. Actually the specification doesn't explicitely mention which XML version to support but back at that time there was no XML version 1.0.

The spec is thus not very clear, however I actually tried using this crate to write authentication code for [OpenSim](http://opensimulator.org/wiki/Main_Page) and had some issues (and struggled figuring out what the issue was) until I realized that the server quietly rejects any kind of XML v1.1 request.

The two options I see are:

- Defaulting to XML v1.0
- Allowing the version to be specified explicitely (and have it default to one or the other version by default).

Any opinion on this?

**Edit:** I just realized that it's only in `write_as_xml` where version 1.0 is mentioned, so it might also just have been unintentional.

**Comment by jonas-schievink** [comment]
I'd have to look into the spec to see which benefits XML v1.1 gives us.

**Comment by jonas-schievink** [comment]
So it seems like the [changes in the XML v1.1 spec](https://www.w3.org/TR/xml11/#sec-xml11) shouldn't really affect XML-RPC. I've merged #13 to fix this.
