### ISSUE TITLE
empty strings lead to UnexpectedXML error

### ISSUE THREAD

**Issue by Nervengift** [jonas-schievink/xml-rpc-rs#18]
Consider the following XML snippet: `<member><name>foo</name><value><string/></value></member>`  (got that from an actual xml-rpc API)

I would expect it to become a map entry like `"foo" : ""` but instead it gives me an error `Err(ParseError(UnexpectedXml { expected: "expected characters", position: 1:531 }))` (the position is the start of `<string/>`)

I guess the problem is the assumption that strings have to contain a `XmlEvent::Character` at https://github.com/jonas-schievink/xml-rpc-rs/blob/master/src/parser.rs#L201

**Comment by jonas-schievink** [comment]
Thanks for the report. Same thing happens for empty `<base64>` values. Other empty values are correctly rejected (I think - the spec isn't very clear on what should happen).

**Comment by mseri** [comment]
This is still not working. An empty string can be represented also as `<value></value>`.

Try for example with
```rust
    #[test]
    fn parses_empty_value_response() {
        assert_ok(read_response(r##"
<?xml version="1.0"?>
<methodResponse>
    <params>
        <param>
            <value></value>
        </param>
    </params>
</methodResponse>
"##));
    }

    #[test]
    fn parses_empty_value_in_struct_response() {
        assert_ok(read_response(r##"
<?xml version="1.0"?>
<methodResponse>
    <params>
        <param><value>
        <struct><member>
            <name>Test</name>
            <value></value>
        </member></struct>
        </value></param>
    </params>
</methodResponse>
"##));
    }
```

It fails with
```
failures:
---- parser::tests::parses_empty_value_response stdout ----
        thread 'parser::tests::parses_empty_value_response' panicked at 'assert_ok called on Err value: UnexpectedXml { expected: "type tag or characters", position: 6:20 }', src/parser.rs:316:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- parser::tests::parses_empty_value_in_struct_response stdout ----
        thread 'parser::tests::parses_empty_value_in_struct_response' panicked at 'assert_ok called on Err value: UnexpectedXml { expected: "type tag or characters", position: 8:20 }', src/parser.rs:316:22
```

**Comment by jonas-schievink** [comment]
@mseri Thanks for the test cases! I've pushed a commit which should hopefully fix this.

**Comment by mseri** [comment]
Thanks!
