### ISSUE TITLE
[Fetature Request] Allow set custom UserAgent

### ISSUE THREAD

**Issue by vaurelios** [jonas-schievink/xml-rpc-rs#20]
Some APIs requires a custom user-agent (OpenSubtitles for example), would be great have support to custom user-agent.

Maybe a argument to `call` to permit set custom headers?

**Comment by jonas-schievink** [comment]
Maybe the best course of action would be similar to #19, where a more advanced `call_with_headers` method is added to `Client`?

**Comment by vaurelios** [comment]
+1 i like the idea of `call_with_headers`

**Comment by jonas-schievink** [comment]
#21 allows this and similar modifications to the request, closing.
