### ISSUE TITLE
Old hyper version

### ISSUE THREAD

**Issue by leoschwarz** [jonas-schievink/xml-rpc-rs#23]
This crate is currently using hyper 0.10.*, which is the non async version.

Personally I would prefer if the crate would not switch to an async API as it just complicates usage (for me) and doesn't provide many gains except if someone was making tons of XML RPC calls, but it is an option and maybe wished for.

Another option would be switching to the [reqwest](https://crates.io/crates/reqwest) crate which uses a recent version of Hyper behind the scenes, but most importantly cookies are missing yet and this might be a requirement here?

**Comment by jonas-schievink** [comment]
Cookies can be set by changing the hyper `RequestBuilder` before the procedure is called ([`Request::call_with`](https://docs.rs/xmlrpc/0.6.0/xmlrpc/struct.Request.html#method.call_with)). There is however no way of receiving cookies from the server.

All that's really needed for complete cookie support is access to the headers that are sent and received, and that should be possible with reqwest, too.

I'm okay with switching to reqwest. Maybe in the future we want to have real support for async hyper, but reqwest looks good for now.
