### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by faulesocke** [jonas-schievink/xml-rpc-rs#42]
In order to implement some specific XML-RPC API, I need to access response cookies and also set request cookies. What is the best way to achieve this with the current code?

**Comment by jonas-schievink** [comment]
Take a look at [examples/custom-header.rs](https://github.com/jonas-schievink/xml-rpc-rs/blob/27e54dece3b6d2f0202503ba70479a1fe426fa5e/examples/custom-header.rs).

**Comment by faulesocke** [comment]
Thank you very much!
