### ISSUE TITLE
New release with updated dependencies

### ISSUE THREAD

**Issue by internetionals** [jonas-schievink/xml-rpc-rs#67]
There are some pull requests open for purely dependency updates. It would be really helpful if those could be merged and new release could be published (eg. 0.14.1).

Especially:
- #66
- #64 

But the bump for #58 would also be nice as it reduces the `cargo outdated` reporting. I understand the sentiment in making it an internal only dependency, but a simple bump for now couldn't hurt.

**Comment by jonas-schievink** [comment]
[0.15.0](https://github.com/jonas-schievink/xml-rpc-rs/releases/tag/v0.15.0) has been released
